POST http://localhost:3333/cursos
Content-Type: application/json

{
  "title": "Curso de Cozinha e cuidados"
}

###

GET http://localhost:3333/cursos

###

GET http://localhost:3333/cursos/7bd9e8c1-0f4a-4a79-8da8-472be21b9f65

###

DELETE http://localhost:3333/cursos/88a71712-afe8-4891-a4c3-d420961410bb