POST http://localhost:3333/cursos
Content-Type: application/json

{
  "title": "Curso de Jumento"
}

###

GET http://localhost:3333/cursos

###

GET http://localhost:3333/cursos/7

###

DELETE http://localhost:3333/cursos/3